name: from issue to card

on:
  issues:
    types: [opened]

jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Information
        run: |
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Repository: ${{ github.repository }}"
          echo "Project Token: ${{ secrets.PROJECT_TOKEN }}"
          echo "Project Location: ahmed710/projects"
          echo "Project Name: kanban_broker"
          echo "Column Name: backlog"

      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v3
        with:
          project-name: kanban_broker
          column-name: backlog
          issue-number: ${{ github.event.issue.number }}
          token: ${{ secrets.PROJECT_TOKEN }}
          project-location: ahmed710/projects
          repository: ahmed710/Assu
