name: Converted card to issue

on:
  projects_v2:
    types: [converted]

jobs:
  converted-card-to-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: github.event.action
        run: echo "${{github.event.action}}"

      - name:  github.event.project_card
        run: echo "${{github.event.project_card}}"


