name: Add bugs to bugs project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          # Update project-url to target your project in your profile
          project-url: https://github.com/users/ahmed710/projects/6
          github-token: ${{ secrets.PROJECT_TOKEN }}
          labeled: bug, needs-triage
          label-operator: OR


