name: Add bugs to bugs project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project board
        env:
          PROJECT_URL: https://api.github.com/projects/6
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.inertia-preview+json" \
            -d '{"content_id":$ISSUE_NUMBER,"content_type":"Issue"}' \
            $PROJECT_URL/columns/123/cards
