name: Converted card to issue

on:
  project_card:
    types: [converted]

jobs:
  converted-card-to-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debug Event
        run: |
          echo hetha test echo
          echo "hello world"

      - name: event
        run: echo "${{github.event.action}}"


